{% set name = "google-cloud-dlp" %}
{% set version = "3.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e91e0248ec81f9b79350f36d8fcc1073bb9098c5318723bc95e6d5d0f0eed4b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - grpc
    - google.cloud.dlp
    - google.cloud.dlp_v2
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-dlp
  summary: Google Cloud Dlp API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "Cloud Data Loss Prevention (DLP) API provides methods for detection, risk analysis, and de-identification of privacy-sensitive fragments in text, images, and Google Cloud Platform storage repositories.\nSee the [quick start guide](https://googleapis.dev/python/dlp/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dlp/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-dlp

extra:
  recipe-maintainers:
    - xylar
    - parthea
